### PR TITLE
Enhancement/#14 return xml on exception

### LINKED ISSUE #14: If applicable return xml request in a response on exceptions
## Problem

If a code validation request or invoice (even more so the invoice) fails due to an exception - meaning it likely was never sent - the request body is lost. You may want to save failed requests somewhere to retry them manually or atleast for trouble shooting since they are important

## Solution

Improve exception handling. On exceptions before the XML is built in the first place, throw an exception. On exceptions thrown after the XML is built, catch exceptions and return a DigaApiResponse object with errors (containing the exception message) but with the "raw xml request body" set

### PR DESCRIPTION
**Pull request by fongie**
# Pull Request

### Description

- clean up exceptions to make it as simple as possible for users to find out what is happening
- IF xml request has been created when an exception occurs internally, return a response object with the error and with the xml request present. This enables users to store f.e a failed invoice or code validation request for use later, rather than it getting lost after the exception is thrown

### Closes

closes #14

### CODE REVIEW

File: src/main/java/com/alextherapeutics/diga/implementation/DigaXmlJaxbRequestReader.java [hunk 1]
```diff
@@ -59,36 +59,45 @@ public DigaXmlJaxbRequestReader() throws JAXBException {
...
+
+            // appendix 4 at https://www.gkv-datenaustausch.de/leistungserbringer/digitale_gesundheitsanwendungen/digitale_gesundheitsanwendungen.jsp
+            // seems to differ from the current xsd schema definition. watch for changes here
+            return DigaCodeValidationResponse.builder()
+                    .rawXmlResponseBody(bytes)
+                    .hasError(response.getNachrichtentyp().equals(NachrichtentypStp.FEH))
+                    .errors(getCodeValidationErrors(response))
+                    .validatedDigaCode(response.getAntwort() == null ? null : response.getAntwort().getFreischaltcode())
+                    .dayOfServiceProvision(response.getAntwort() == null ? null : response.getAntwort().getTagDerLeistungserbringung().toGregorianCalendar().getTime())
+                    .validatedDigaveid(response.getAntwort() == null ? null : response.getAntwort().getDiGAVEID())
```
Comment (StaffanKilnes) [inline src/main/java/com/alextherapeutics/diga/implementation/DigaXmlJaxbRequestReader.java:93]: Can you do "||" here instead of "null ? null : ..."?

**Review by StaffanKilnes — CHANGES_REQUESTED** [review]
Cool stuff!

File: src/main/java/com/alextherapeutics/diga/implementation/DigaXmlJaxbRequestReader.java (hunk 1 above)
Comment (fongie) [reply src/main/java/com/alextherapeutics/diga/implementation/DigaXmlJaxbRequestReader.java:93]: nope! it is not possible in Java :)
